---
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2026 SUSE Software Solutions
#
# Authors: Daniel Wagner <dwagner@suse.de>

name: Python Sanity

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    name: Lint (${{ matrix.container }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container:
          - ghcr.io/linux-nvme/nvmetcli-debian:latest
          - ghcr.io/linux-nvme/nvmetcli-fedora:latest
          - ghcr.io/linux-nvme/nvmetcli-tumbleweed:latest

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: flake8
        run: python3 -m flake8 nvmet/ nvmetcli

      - name: pylint
        run: python3 -m pylint --disable=all --enable=E nvmet/ nvmetcli
