---
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2026 SUSE Software Solutions
#
# Authors: Daniel Wagner <dwagner@suse.de>

name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  testsuite:
    runs-on: arc-vm-nvmetcli-cph
    timeout-minutes: 1200

    env:
      CHECKOUT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

    strategy:
      fail-fast: false
      matrix:
        container:
          - ghcr.io/linux-nvme/nvmetcli-debian-containerdisk:next
          - ghcr.io/linux-nvme/nvmetcli-fedora-containerdisk:next
          - ghcr.io/linux-nvme/nvmetcli-tumbleweed-containerdisk:next

    name: >
      testsuite (${{ matrix.container }})

    steps:
      - name: Checkout blktests-ci
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: linux-blktests/blktests-ci

      - name: Run in VM
        uses: ./.github/actions/kubevirt-action
        with:
          container_disk_image: ${{ matrix.container }}
          run_cmds: |
            git clone https://github.com/${{ github.repository }} nvmetcli
            git config --global --add safe.directory nvmetcli
            cd nvmetcli
            git checkout "${CHECKOUT_SHA}"

            sudo modprobe nvmet
            sudo make test
